version: '3'


services:
  broker:
    build: broker
    ports:
      - "9000:9000"


  auldfellas:
    build: auldfellas
    depends_on:
      - broker


  dodgygeezers:
    build: dodgygeezers
    depends_on:
      - broker


  girlsallowed:
    build: girlsallowed
    depends_on:
      - broker







