version: '3'


services:
  broker:
    build: broker
    ports:
      - "9000:9000"
    environment:
      - CONTAINER_NAME = broker


  auldfellas:
    build: auldfellas
    depends_on:
      - broker
    environment:
      - CONTAINER_NAME = auldfellas


  dodgygeezers:
    build: dodgygeezers
    depends_on:
      - broker
    environment:
      - CONTAINER_NAME = dodgygeezers


  girlsallowed:
    build: girlsallowed
    depends_on:
      - broker
    environment:
      - CONTAINER_NAME = girlsallowed

