version: '3.6'

services:
  broker:
    build: broker
    ports:
      - "2550:2550"
    environment:
      - HOSTNAME=broker

  auldfellas:
    build: auldfellas
    depends_on:
      - broker
    environment:
      - HOSTNAME=auldfellas
    ports:
      - "2551:2551"


  dodgygeezers:
    build: dodgygeezers
    depends_on:
      - broker
    environment:
      - HOSTNAME=dodgygeezers
    ports:
      - "2553:2553"


  girlsallowed:
    build: girlsallowed
    depends_on:
      - broker
    environment:
      - HOSTNAME=girlsallowed
    ports:
      - "2552:2552"

  client:
    build: client
    environment:
      - HOSTNAME=client
    depends_on:
      - broker
      - auldfellas
      - dodgygeezers
      - girlsallowed

