FROM openjdk:18
COPY target/dodgygeezers-0.0.1-jar-with-dependencies.jar /dodgygeezers-0.0.1-jar-with-dependencies.jar
CMD sleep 5 && /usr/bin/java -jar /dodgygeezers-0.0.1-jar-with-dependencies.jar $RMI_SERVER