FROM openjdk:18
COPY target/auldfellas-0.0.1-jar-with-dependencies.jar /auldfellas-0.0.1-jar-with-dependencies.jar
CMD sleep 5 && /usr/bin/java -jar /auldfellas-0.0.1-jar-with-dependencies.jar $RMI_SERVER