version: '3.6'

services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:latest
    ports:
      - 8161:8161
      - 61616:61616

  broker:
    build: broker
    depends_on:
      - activemq
    environment:
      - SERVER_MOM=activemq

  auldfellas:
    build: auldfellas
    depends_on:
      - activemq
    environment:
      - SERVER_MOM=activemq

  dodgygeezers:
    build: dodgygeezers
    depends_on:
      - activemq
    environment:
      - SERVER_MOM=activemq

  girlsallowed:
    build: girlsallowed
    depends_on:
      - activemq
    environment:
      - SERVER_MOM=activemq


