FROM openjdk:8-jdk-alpine
COPY target/dodgygeezers-0.0.1-jar-with-dependencies.jar /dodgygeezers-0.0.1-jar-with-dependencies.jar
#EXPOSE 9002
CMD sleep 3 && /usr/bin/java -jar /dodgygeezers-0.0.1-jar-with-dependencies.jar $WS_URL