FROM openjdk:18
COPY target/girlsallowed-0.0.1-jar-with-dependencies.jar /girlsallowed-0.0.1-jar-with-dependencies.jar
CMD sleep 5 && /usr/bin/java -jar /girlsallowed-0.0.1-jar-with-dependencies.jar $RMI_SERVER